apiVersion: v1
kind: ConfigMap
metadata:
  name: mssqldata-configmap
data:
  schemaanddata.sql: |-
    IF DB_ID('employeedb') IS NULL
        CREATE DATABASE employeedb
    GO
    USE employeedb
    GO
    IF  NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[EMPLOYEE]') AND type in (N'U'))
    BEGIN
        CREATE TABLE EMPLOYEE (
            Emp_NO INTEGER PRIMARY KEY,
            Emp_Name TEXT NOT NULL,
            Emp_Add TEXT NOT NULL,
            Emp_Phone TEXT NOT NULL,
            Dept_No TEXT NOT NULL,
            Dept_Name TEXT NOT NULL,
            Salary TEXT NOT NULL
        );
    INSERT INTO EMPLOYEE VALUES (0001, 'Ramesh', 'GNoida','9855498465', '3445', 'Tech','25000');
    INSERT INTO EMPLOYEE VALUES (0002, 'Suresh', 'GNoida','98565498465', '0072', 'Admin','75000');
    INSERT INTO EMPLOYEE VALUES (0003, 'Rajesh', 'GNoida','9855497865', '2324', 'IT','28000');
    INSERT INTO EMPLOYEE VALUES (0004, 'Shyamu', 'BSB','9853698465', '8883', 'IT','35000');
    INSERT INTO EMPLOYEE VALUES (0005, 'Ramu', 'BSB','9855498235', '74568', 'HR','96000');
    INSERT INTO EMPLOYEE VALUES (0006, 'Mahesh', 'GNoida','9851678465', '1238', 'Sales','25000');
    INSERT INTO EMPLOYEE VALUES (0007, 'Chaman', 'BSBS','9856723465', '7634', 'Tech','215000');
    END



