apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mssql
spec:
  serviceName: mssql-service
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  updateStrategy:
    type: OnDelete
    rollingUpdate: null
  template:
    metadata:
      labels:
        app: mssql
    spec:
      terminationGracePeriodSeconds: 10
      securityContext:
        fsGroup: 1000
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/rhel/server:2019-latest
        lifecycle:
          postStart:
            exec:
              command:
                - /bin/bash
                - -c
                - |
                  /opt/mssql/bin/sqlservr &
                  sleep 30
                  /opt/mssql-tools/bin/sqlcmd -U sa -P $MSSQL_SA_PASSWORD -l 30 -e -i /var/opt/mssqldata/schemaanddata.sql
        ports:
        - containerPort: 1433
          name: tcpsql
        env:
        - name: MSSQL_PID
          value: "Developer"
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql-secret
              key: SA_PASSWORD 
        volumeMounts:
        - name: mssqldb
          mountPath: /var/opt/mssql
        - name: mssqldataconfigmap
          mountPath: /var/opt/mssqldata
      volumes:
      - name: mssqldb
        persistentVolumeClaim:
          claimName: mssql-pvc
      - name: mssqldataconfigmap
        configMap:
          name: mssqldata-configmap