apiVersion: v1
kind: ConfigMap
metadata:
  name: mssql-configmap
data:
  appsettings.json: |-
    {
      "Logging": {
        "LogLevel": {
          "Default": "Debug",
          "System": "Debug",
          "Microsoft": "Error"
        }
      },
      "ConnectionStrings": {
        "Con": "Data Source=mssql-service.default.svc.cluster.local;User ID=sa;Password=$DB_PASSWORD$;Initial Catalog=employeedb;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False"
      }
    }