apiVersion: v1
kind: Service
metadata:
  name: mssql-service
spec:
  clusterIP: None
  selector:
    statefulset.kubernetes.io/pod-name: mssql-0
  ports:
  - name: tcpsql
    protocol: TCP
    port: 1433
    targetPort: 1433