apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssqlwebapi-deployment
  labels:
    app: mssqlwebapi
spec:
  replicas: 4
  minReadySeconds: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: mssqlwebapi
  template:
    metadata:
      labels:
        app: mssqlwebapi
    spec:
      containers:
      - name: mssqlwebapi-container
        image: ateet1989/mssqlwebapi:v5
        resources:
          requests:
            memory: "200Mi"
            cpu: "50m"
          limits:
            memory: "400Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
          name: webapi-http
        readinessProbe:
          httpGet:
            port: 80
            path: /healthz
          successThreshold: 3
          initialDelaySeconds: 10
          timeoutSeconds: 20
          periodSeconds: 5
          failureThreshold: 3
        env:
        - name: MSSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql-secret
              key: SA_PASSWORD
        volumeMounts:
        - name: mssqlconfigmap
          mountPath: /app/config
      volumes:
      - name: mssqlconfigmap
        configMap:
          name: mssql-configmap
        