apiVersion: v1
kind: Service
metadata:
  name: mssqlwebapi-service
spec:
  selector:
    app: mssqlwebapi
  type: LoadBalancer
  ports:
    - name: mssqlwebapi-port
      port: 8080
      targetPort: 80